apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastflow-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastflow-executor
  template:
    metadata:
      labels:
        app: fastflow-executor
    spec:
      containers:
        - name: api
          image: yourrepo/fastflow-executor:latest
          ports:
            - containerPort: 8000
          env:
            - name: RUST_LOG
              value: info
---
apiVersion: v1
kind: Service
metadata:
  name: fastflow-executor
spec:
  type: ClusterIP
  selector:
    app: fastflow-executor
  ports:
    - port: 80
      targetPort: 8000
